POST http://localhost:4000/dev/travel/destination/create 
Accept: application/json

{
	"identifier": "new-user",
    "device": {
        "name": "new-device",
        "model": "no-phone",
        "matcher": "some-matcher"
    },
    "title": "welcome",
    "description": "welcome-description",
    "accessCode": "code"
}
