POST http://localhost:4000/devl/travel/destination/fetch 
Accept: application/json

{
	"identifier": "k8kwackd-tk1ya-t6zjhmds1s-ncoe5h36s0",
    "device": {
        "name": "new-device",
        "model": "no-phone",
        "matcher": "some-matcher"
    }
}
